### ISSUE TITLE
failure installing with sample playbook

### ISSUE THREAD

**Issue by beargiles** [stuvusIT/slapd-config#19]
I get this error when using the sample playbook (slightly modified) on an Ubuntu 18.04 instance.

```json
{
    "_ansible_parsed": true,
    "stderr_lines": [
        "ldap_add: Other (e.g., implementation specific) error (80)",
        "\tadditional info: <olcModuleLoad> handler exited with 1"
    ],
    "changed": false,
    "end": "2019-01-07 18:15:01.382772",
    "_ansible_no_log": false,
    "stdout": "adding new entry \"cn=modules{0},cn=config\"",
    "cmd": [
        "/usr/local/bin/slapd-global-modules",
        "%2Frun%2Fslapd%2Fldapi",
        "cn=root,cn=config",
        "/usr/lib/openldap",
        "True",
        "memberof"
    ],
    "rc": 80,
    "start": "2019-01-07 18:15:01.353884",
    "stderr": "ldap_add: Other (e.g., implementation specific) error (80)\n\tadditional info: <olcModuleLoad> handler exited with 1",
    "delta": "0:00:00.028888",
    "invocation": {
        "module_args": {
            "creates": null,
            "executable": null,
            "_uses_shell": false,
            "_raw_params": "/usr/local/bin/slapd-global-modules \"%2Frun%2Fslapd%2Fldapi\" \"cn=root,cn=config\" \"/usr/lib/openldap\" \"True\" \"memberof\"",
            "removes": null,
            "argv": null,
            "warn": true,
            "chdir": null,
            "stdin": null
        }
    },
    "stdout_lines": [
        "adding new entry \"cn=modules{0},cn=config\""
    ],
    "msg": "non-zero return code"
}
```

Playbook:
```yml
- name: install openldap
  hosts: launched
  become: yes
  user: ubuntu
  vars:
     slapd_modules_path: /usr/lib/openldap
     slapd_olc_rootdn_password: water
     slapd_mdb_rootdn_password: water
     slapd_monitor_rootdn_password: water
     slapd_additional_modules: [ 'memberof' ]
     slapd_mdb_config:
        olcSuffix: "dc=example,dc=com"
     slapd_mdb_overlays:
        memberof:
           oldOverlay: memberof
           objectClass: olcMemberOf
           olcMemberOfDangling: ignore
  roles:
   - stuvusit.slapd-base
   - stuvusit.slapd-config
```

where the 'launched' is actually a newly created EC2 instance.

**Comment by beargiles** [comment]
I made some progress... added a bunch of missing properties. I get the same results when I execute this from the command line - no output but a return code of 1.

Error:

```json
{
    "_ansible_parsed": true,
    "stderr_lines": [],
    "changed": true,
    "end": "2019-01-08 16:59:55.576130",
    "_ansible_no_log": false,
    "stdout": "",
    "cmd": [
        "/bin/systemd-tmpfiles",
        "--create"
    ],
    "rc": 1,
    "start": "2019-01-08 16:59:55.567063",
    "stderr": "",
    "delta": "0:00:00.009067",
    "invocation": {
        "module_args": {
            "creates": null,
            "executable": null,
            "_uses_shell": false,
            "_raw_params": "/bin/systemd-tmpfiles --create",
            "removes": null,
            "argv": null,
            "warn": true,
            "chdir": null,
            "stdin": null
        }
    },
    "stdout_lines": [],
    "msg": "non-zero return code"
}
```

Playbook:

```yml
- name: install openldap
  hosts: launched
  become: yes
  user: ubuntu
  vars:
     slapd_run_dir: /var/run/ldapi
     slapd_ldapi_socket: /var/run/slapd/ldapi
     slapd_modules_path: /usr/lib/openldap
     slapd_additional_modules: [ 'memberof' ]
     slapd_mdb_dir: /var/lib/ldap
     slapd_mdb_rootdn_password: water
     slapd_mdb_config:
        olcSuffix: "dc=example,dc=com"
     slapd_mdb_overlays:
        memberof:
           oldOverlay: memberof
           objectClass: olcMemberOf
           olcMemberOfDangling: ignore
     slapd_monitor_rootdn_password: water
     slapd_olc_dir: /etc/ldap/slapd.d
     slapd_olc_rootdn: "dc=example,dc=com"
     slapd_olc_rootdn_password: water
  roles:
   - stuvusit.slapd-base
   - stuvusit.slapd-config
```
